name: build

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:

   test:
     runs-on: ubuntu-latest
     steps:
       - name: Git checkout
         uses: actions/checkout@v1

       - name: Prepare java
         uses: actions/setup-java@v3
         with:
          distribution: 'temurin'
          java-version: '8'

       - name: Install clojure tools
         uses: DeLaGuardo/setup-clojure@13.0
         with:
          lein: 2.9.1

       - uses: actions/setup-node@v4
         with:
          node-version: '20'

       - name: Run JVM tests
         run: lein test

       - name: Run node tests
         run: lein doo node once
